# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import rpc_pb2 as rpc__pb2


class ElectrumBridgeStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SetHdSeed = channel.unary_unary(
        '/electrumbridge.ElectrumBridge/SetHdSeed',
        request_serializer=rpc__pb2.SetHdSeedRequest.SerializeToString,
        response_deserializer=rpc__pb2.SetHdSeedResponse.FromString,
        )
    self.NewAddress = channel.unary_unary(
        '/electrumbridge.ElectrumBridge/NewAddress',
        request_serializer=rpc__pb2.NewAddressRequest.SerializeToString,
        response_deserializer=rpc__pb2.NewAddressResponse.FromString,
        )
    self.ConfirmedBalance = channel.unary_unary(
        '/electrumbridge.ElectrumBridge/ConfirmedBalance',
        request_serializer=rpc__pb2.ConfirmedBalanceRequest.SerializeToString,
        response_deserializer=rpc__pb2.ConfirmedBalanceResponse.FromString,
        )
    self.FetchRootKey = channel.unary_unary(
        '/electrumbridge.ElectrumBridge/FetchRootKey',
        request_serializer=rpc__pb2.FetchRootKeyRequest.SerializeToString,
        response_deserializer=rpc__pb2.FetchRootKeyResponse.FromString,
        )
    self.ListUnspentWitness = channel.unary_unary(
        '/electrumbridge.ElectrumBridge/ListUnspentWitness',
        request_serializer=rpc__pb2.ListUnspentWitnessRequest.SerializeToString,
        response_deserializer=rpc__pb2.ListUnspentWitnessResponse.FromString,
        )
    self.NewRawKey = channel.unary_unary(
        '/electrumbridge.ElectrumBridge/NewRawKey',
        request_serializer=rpc__pb2.NewRawKeyRequest.SerializeToString,
        response_deserializer=rpc__pb2.NewRawKeyResponse.FromString,
        )
    self.FetchInputInfo = channel.unary_unary(
        '/electrumbridge.ElectrumBridge/FetchInputInfo',
        request_serializer=rpc__pb2.FetchInputInfoRequest.SerializeToString,
        response_deserializer=rpc__pb2.FetchInputInfoResponse.FromString,
        )
    self.ComputeInputScript = channel.unary_unary(
        '/electrumbridge.ElectrumBridge/ComputeInputScript',
        request_serializer=rpc__pb2.ComputeInputScriptRequest.SerializeToString,
        response_deserializer=rpc__pb2.ComputeInputScriptResponse.FromString,
        )
    self.SignOutputRaw = channel.unary_unary(
        '/electrumbridge.ElectrumBridge/SignOutputRaw',
        request_serializer=rpc__pb2.SignOutputRawRequest.SerializeToString,
        response_deserializer=rpc__pb2.SignOutputRawResponse.FromString,
        )
    self.PublishTransaction = channel.unary_unary(
        '/electrumbridge.ElectrumBridge/PublishTransaction',
        request_serializer=rpc__pb2.PublishTransactionRequest.SerializeToString,
        response_deserializer=rpc__pb2.PublishTransactionResponse.FromString,
        )
    self.LockOutpoint = channel.unary_unary(
        '/electrumbridge.ElectrumBridge/LockOutpoint',
        request_serializer=rpc__pb2.LockOutpointRequest.SerializeToString,
        response_deserializer=rpc__pb2.LockOutpointResponse.FromString,
        )
    self.UnlockOutpoint = channel.unary_unary(
        '/electrumbridge.ElectrumBridge/UnlockOutpoint',
        request_serializer=rpc__pb2.UnlockOutpointRequest.SerializeToString,
        response_deserializer=rpc__pb2.UnlockOutpointResponse.FromString,
        )
    self.ListTransactionDetails = channel.unary_unary(
        '/electrumbridge.ElectrumBridge/ListTransactionDetails',
        request_serializer=rpc__pb2.ListTransactionDetailsRequest.SerializeToString,
        response_deserializer=rpc__pb2.ListTransactionDetailsResponse.FromString,
        )
    self.SendOutputs = channel.unary_unary(
        '/electrumbridge.ElectrumBridge/SendOutputs',
        request_serializer=rpc__pb2.SendOutputsRequest.SerializeToString,
        response_deserializer=rpc__pb2.SendOutputsResponse.FromString,
        )
    self.IsSynced = channel.unary_unary(
        '/electrumbridge.ElectrumBridge/IsSynced',
        request_serializer=rpc__pb2.IsSyncedRequest.SerializeToString,
        response_deserializer=rpc__pb2.IsSyncedResponse.FromString,
        )
    self.SignMessage = channel.unary_unary(
        '/electrumbridge.ElectrumBridge/SignMessage',
        request_serializer=rpc__pb2.SignMessageRequest.SerializeToString,
        response_deserializer=rpc__pb2.SignMessageResponse.FromString,
        )


class ElectrumBridgeServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SetHdSeed(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def NewAddress(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ConfirmedBalance(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FetchRootKey(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListUnspentWitness(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def NewRawKey(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FetchInputInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ComputeInputScript(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SignOutputRaw(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PublishTransaction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LockOutpoint(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UnlockOutpoint(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListTransactionDetails(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendOutputs(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def IsSynced(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SignMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ElectrumBridgeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SetHdSeed': grpc.unary_unary_rpc_method_handler(
          servicer.SetHdSeed,
          request_deserializer=rpc__pb2.SetHdSeedRequest.FromString,
          response_serializer=rpc__pb2.SetHdSeedResponse.SerializeToString,
      ),
      'NewAddress': grpc.unary_unary_rpc_method_handler(
          servicer.NewAddress,
          request_deserializer=rpc__pb2.NewAddressRequest.FromString,
          response_serializer=rpc__pb2.NewAddressResponse.SerializeToString,
      ),
      'ConfirmedBalance': grpc.unary_unary_rpc_method_handler(
          servicer.ConfirmedBalance,
          request_deserializer=rpc__pb2.ConfirmedBalanceRequest.FromString,
          response_serializer=rpc__pb2.ConfirmedBalanceResponse.SerializeToString,
      ),
      'FetchRootKey': grpc.unary_unary_rpc_method_handler(
          servicer.FetchRootKey,
          request_deserializer=rpc__pb2.FetchRootKeyRequest.FromString,
          response_serializer=rpc__pb2.FetchRootKeyResponse.SerializeToString,
      ),
      'ListUnspentWitness': grpc.unary_unary_rpc_method_handler(
          servicer.ListUnspentWitness,
          request_deserializer=rpc__pb2.ListUnspentWitnessRequest.FromString,
          response_serializer=rpc__pb2.ListUnspentWitnessResponse.SerializeToString,
      ),
      'NewRawKey': grpc.unary_unary_rpc_method_handler(
          servicer.NewRawKey,
          request_deserializer=rpc__pb2.NewRawKeyRequest.FromString,
          response_serializer=rpc__pb2.NewRawKeyResponse.SerializeToString,
      ),
      'FetchInputInfo': grpc.unary_unary_rpc_method_handler(
          servicer.FetchInputInfo,
          request_deserializer=rpc__pb2.FetchInputInfoRequest.FromString,
          response_serializer=rpc__pb2.FetchInputInfoResponse.SerializeToString,
      ),
      'ComputeInputScript': grpc.unary_unary_rpc_method_handler(
          servicer.ComputeInputScript,
          request_deserializer=rpc__pb2.ComputeInputScriptRequest.FromString,
          response_serializer=rpc__pb2.ComputeInputScriptResponse.SerializeToString,
      ),
      'SignOutputRaw': grpc.unary_unary_rpc_method_handler(
          servicer.SignOutputRaw,
          request_deserializer=rpc__pb2.SignOutputRawRequest.FromString,
          response_serializer=rpc__pb2.SignOutputRawResponse.SerializeToString,
      ),
      'PublishTransaction': grpc.unary_unary_rpc_method_handler(
          servicer.PublishTransaction,
          request_deserializer=rpc__pb2.PublishTransactionRequest.FromString,
          response_serializer=rpc__pb2.PublishTransactionResponse.SerializeToString,
      ),
      'LockOutpoint': grpc.unary_unary_rpc_method_handler(
          servicer.LockOutpoint,
          request_deserializer=rpc__pb2.LockOutpointRequest.FromString,
          response_serializer=rpc__pb2.LockOutpointResponse.SerializeToString,
      ),
      'UnlockOutpoint': grpc.unary_unary_rpc_method_handler(
          servicer.UnlockOutpoint,
          request_deserializer=rpc__pb2.UnlockOutpointRequest.FromString,
          response_serializer=rpc__pb2.UnlockOutpointResponse.SerializeToString,
      ),
      'ListTransactionDetails': grpc.unary_unary_rpc_method_handler(
          servicer.ListTransactionDetails,
          request_deserializer=rpc__pb2.ListTransactionDetailsRequest.FromString,
          response_serializer=rpc__pb2.ListTransactionDetailsResponse.SerializeToString,
      ),
      'SendOutputs': grpc.unary_unary_rpc_method_handler(
          servicer.SendOutputs,
          request_deserializer=rpc__pb2.SendOutputsRequest.FromString,
          response_serializer=rpc__pb2.SendOutputsResponse.SerializeToString,
      ),
      'IsSynced': grpc.unary_unary_rpc_method_handler(
          servicer.IsSynced,
          request_deserializer=rpc__pb2.IsSyncedRequest.FromString,
          response_serializer=rpc__pb2.IsSyncedResponse.SerializeToString,
      ),
      'SignMessage': grpc.unary_unary_rpc_method_handler(
          servicer.SignMessage,
          request_deserializer=rpc__pb2.SignMessageRequest.FromString,
          response_serializer=rpc__pb2.SignMessageResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'electrumbridge.ElectrumBridge', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
